chagaun_prj/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic import TemplateView
import debug_toolbar
from page import views 

#views : page->views
urlpatterns = [
    path('', views.main),
    path('login/', include('login.urls', namespace="login")),
    path('clipliner/', include('clipliner.urls', namespace="clipliner")),
    path('clipporter/', include('clipporter.urls', namespace="clipporter")),
    path('cliptrailer/', include('cliptrailer.urls', namespace="cliptrailer")),
    path('clipvoicer/', include('clipvoicer.urls', namespace="clipvoicer")),
    path('klicker/', include('klicker.urls', namespace="klicker")),
    path('search/', include('search.urls', namespace="search")),
    path('feedback/', include('feedback.urls', namespace="feedback")),
    path('learnus/', include('learnus.urls', namespace="learnus")),
    path('sitemap.xml/', views.sitemap),
    path('sitemap_google.xml/', views.sitemap_google),
    path('robots.txt/', views.robots),
    path('librdown/<str:filename>', views.libr_download, name="download-libr"),
    path('download/<str:filename>', views.setup_download, name="download-setup"),
    path('download/patch/<name3>/<str:filename>', views.patch_download, name="download-patch"),
    path('summernote/', include('django_summernote.urls')), # 썸머노트 업로드
    path('admin/', admin.site.urls),
    path('api/v1/signup/code', views.api_v1_signup_code),
    path('api/v1/signup', views.api_v1_signup),
    path('api/v1/login', views.api_v1_login),
    path('api/v1/charge', views.api_v1_charge),
    path('api/v1/pw/change', views.api_v1_pw_change),
    path('api/v1/pw/reset', views.api_v1_pw_reset),
    path('api/v1/inquiry', views.api_v1_inquiry),
    path('Member/Logout', views.api_v1_logout),
    path('<name1>/', views.category1),
    path('<name1>/<name2>', views.category2),
    path('<name1>/<name2>/<name3>', views.category3),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

feedback/urls.py
from django.urls import path
from feedback import views

app_name = "feedback"
 
urlpatterns = [
    path('list/', views.list, name='list'),
    path('create', views.create, name='create'),
    path('edit/(?P<id>\d+)/$', views.edit, name='edit')
]

main/urls.py
from django.urls import path
from main import views

app_name = "main"
 
urlpatterns = [
    path('', views.main, name='main'),
]

feedback/models.py
from django.db import models
 
class Feedback(models.Model):
     name = models.CharField(max_length=100)
     email = models.EmailField()
     comment = models.TextField(null=True)
     createDate = models.DateTimeField(auto_now_add=True)

feedback/forms.py
from django.forms import ModelForm
from .models import Feedback
 
class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ['id', 'name','email','comment']

feedback/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import FeedbackForm
 
def list(request):
    feedbacks = Feedback.objects.all()
    return render(request, 'feedback/feedback_list.html.html', {'feedbacks': feedbacks})

def create(request):
    if request.method=='POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/feedback/list/')
    else:
        form = FeedbackForm()
 
    return render(request, 'feedback/feedback_detail.html.html', {'form': form})
 
def edit(request, id):
    fb = Feedback.objects.get(pk=id)
    if request.method=='POST':
        form = FeedbackForm(request.POST, instance=fb)
        if form.is_valid():
            form.save()
        return redirect('/feedback/list/')
    else:
        form = FeedbackForm(instance=fb)
 
    return render(request, 'feedback/feedback_detail.html.html', {'form': form})

feedback/templates/feedback/feedback_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>feedback</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/Contact-Form-Clean.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body>
    <section class="contact-clean">
        <form id="feedback_edit_form" method="post">
            <h2 class="text-center">Feedback</h2>
            <div class="mb-3"><input class="form-control" type="text" name="name" placeholder="Name"></div>
            <div class="mb-3"><input class="form-control is-invalid" type="email" name="email" placeholder="Email"><small class="form-text text-danger">Please enter a correct email address.</small></div>
            <div class="mb-3"><textarea class="form-control" name="message" placeholder="Message" rows="14"></textarea></div>
            <div class="mb-3" style="text-align: center;"><button class="btn btn-primary" type="submit" style="padding-right: 32px;margin-right: 8px;margin-left: 8px;">저장</button><button class="btn btn-primary" type="button" style="margin-right: 8px;margin-left: 8px;" onclick="goBack()">돌아가기</button></div>
        </form>
    </section>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

feedback/templates/feedback/feedback_detail.html.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>feedback</title>
    <link rel="stylesheet" href="{% static 'feedback/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'feedback/assets/css/Contact-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'feedback/assets/css/styles.css' %}">
</head>

<body>
    <section class="contact-clean">
        <form id="feedback_edit_form" method="post">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <div class="mb-3" style="text-align: center;"><button class="btn btn-primary" type="submit" style="padding-right: 32px;margin-right: 8px;margin-left: 8px;">저장</button><button class="btn btn-primary" type="button" style="margin-right: 8px;margin-left: 8px;"><a href="{% url 'feedback:list' %}">돌아가기</a></button></div>
        </form>
    </section>
    <script src="{% static 'feedback/assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

feedback/templates/feedback/feedback_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>feedback</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/Contact-Form-Clean.css">
    <link rel="stylesheet" href="assets/css/styles.css">
</head>

<body>
    <div class="row justify-content-center">
        <div class="col-xl-10 col-xxl-9">
            <div class="card shadow">
                <div class="card-header d-flex flex-wrap justify-content-center align-items-center justify-content-sm-between gap-3">
                    <h5 class="display-6 text-nowrap text-capitalize mb-0">Feedback</h5>
                    <div class="input-group input-group-sm w-auto"><input class="form-control form-control-sm" type="text" id="search_keyword"><button class="btn btn-outline-primary btn-sm" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-search mb-1">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                            </svg></button></div><a id="feedback_add" class="feedback_add" href="#">추가</a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>E-mail</th>
                                    <th>Comment</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="text-truncate" style="max-width: 200px;">Jmeno Prijmení</td>
                                    <td class="text-truncate" style="max-width: 200px;">email.prijmeni@sssssssssssssssgmail.com</td>
                                    <td>Superior</td>
                                    <td class="text-center"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-eye-fill fs-5 text-primary">
                                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"></path>
                                            <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"></path>
                                        </svg></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <nav>
                        <ul class="pagination pagination-sm mb-0 justify-content-center">
                            <li class="page-item"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

feedback/templates/feedback/feedback_list.html.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>feedback</title>
    <link rel="stylesheet" href="{% static 'feedback/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'feedback/assets/css/Contact-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'feedback/assets/css/styles.css' %}">
</head>

<body>
    <div class="row justify-content-center">
        <div class="col-xl-10 col-xxl-9">
            <div class="card shadow">
                <div class="card-header d-flex flex-wrap justify-content-center align-items-center justify-content-sm-between gap-3">
                    <h5 class="display-6 text-nowrap text-capitalize mb-0">Feedback</h5>
                    <div class="input-group input-group-sm w-auto"><input class="form-control form-control-sm" type="text" id="search_keyword"><button class="btn btn-outline-primary btn-sm" type="button"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-search mb-1">
                                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                            </svg></button></div><a id="feedback_add" class="feedback_add" href="{% url 'feedback:create' %}">추가</a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>E-mail</th>
                                    <th>Comment</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in feedbacks %}
                                <tr>
                                    <td class="text-truncate" style="max-width: 200px;"><a href="{% url 'feedback:edit' id=item.id %}">{{item.id}}</td>
                                    <td class="text-truncate" style="max-width: 200px;">{{item.name}}</td>
                                    <td class="text-truncate" style="max-width: 200px;">{{item.email}}</td>
                                    <td class="text-truncate" style="max-width: 200px;">{{item.comment}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <nav>
                        <ul class="pagination pagination-sm mb-0 justify-content-center">
                            <li class="page-item"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'feedback/assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>